### ISSUE TITLE
Instalção

### ISSUE THREAD

**Issue by arteiro** [InFog/moedas#2]
Como instalar pois está indo sempre para localhost direto, algo está errado no index.php ou config.php

**Comment by InFog** [comment]
Olá, @arteiro. Este projeto está parado faz alguns anos. Talvez seja algum problema relacionado a versão do PHP ou do MySQL.

**Comment by arteiro** [comment]
Mas teria a possibilidade de testar?

**Comment by InFog** [comment]
Sim, claro. Você pode usar uma instalação simples de Apache, PHP e MySQL e colocar o código em um diretório. Lembre-se de ativar o mod_rewrite do Apache :)
